### ISSUE TITLE
Add Musée National d'Art Moderne (Centre Pompidou)

### ISSUE THREAD

**Issue by thisisaaronland** [sfomuseum/accession-numbers#29]
Musée National d'Art Moderne (Centre Pompidou)
https://www.mam.paris.fr
(([A-Z]+)(\ |\-|\-)(?:\d+)((\-[0-9]+)|(\ \([0-9]+\))|([A-Z]+))*)
AMPH 204
AMS 403
AMVP-2015-277
AMVP-2015-975
AME 1104 (2)
AMPH 871TER

**Comment by thisisaaronland** [comment]
Added as of `#f7e3a2c`. There is still one test that fails.

**Comment by bwyman** [comment]
let's use this instead:
`(([A-Z]+)([\ \-\-]+)((?:\d+)(([\-0-9\ \(\)A-Z]+))))`
