### ISSUE TITLE
Add Museum of New Zealand Te Papa Tongarewa

### ISSUE THREAD

**Issue by thisisaaronland** [sfomuseum/accession-numbers#32]
Museum of New Zealand Te Papa Tongarewa
https://www.tepapa.govt.nz
(([A-Z]+[0-9]+[\/A-Z]*)|((?:\d+)\-(?:\d+)\-(?:\d++)(\/[A-z\ \-]+)*))
ME001533
2014-0031-1
GH004839
2008-0006-1/A-L to L-L
OL000491
SP082549/A

**Comment by thisisaaronland** [comment]
These have been added as of #aa52195 but tests still fail.

**Comment by bwyman** [comment]
the original regex on top, what you have above, below:
(([A-Z]+[0-9]+[\/A-Z]*)|((?:\d+)\-(?:\d+)\-(?:\d++)(\/[A-z\ \-]+)*))
(([A-Z]+[0-9]+[/A-Z])|((?:\d+)-(?:\d+)-(?:\d++)(/[A-z\ -]+)))

**Comment by bwyman** [comment]
`
(([A-Z]+[0-9]+[\/A-Z]*)|((?:\d+)\-(?:\d+)\-(?:\d++)(\/[A-z\ \-]+)*))
(([A-Z]+[0-9]+[/A-Z])|((?:\d+)-(?:\d+)-(?:\d++)(/[A-z\ -]+)))
`

**Comment by bwyman** [comment]
original regex on top, what you have above, below:
`(([A-Z]+[0-9]+[\/A-Z]*)|((?:\d+)\-(?:\d+)\-(?:\d++)(\/[A-z\ \-]+)*))`
`(([A-Z]+[0-9]+[/A-Z])|((?:\d+)-(?:\d+)-(?:\d++)(/[A-z\ -]+)))`
